app: aws-slack-matchmaking-bot
service: conversation

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  hello:
    handler: handler.match
    events:
      - http:
          path: /match
          method: post
  answer:
    handler: handler.answer

plugins:
  - serverless-plugin-typescript

package:
  exclude:
    - node_modules/**
